-- This file is auto-generated by tools.make_beta_certificate.py
-- Do not edit manually.

import Mathlib
import Mathlib.Tactic.NormNum

import ERURH.Beta.InertiaCertificatesBeta
import ERURH.Beta.GlobalInertiaBeta
import ERURH.Beta.CompositeCertificateBeta

namespace ERURH
namespace Beta

noncomputable def strongInertiaCertificate_beta_numeric : StrongInertiaCertificate_beta :=
{
  C_RMS_beta   := ((1 : ℚ) / (10 : ℚ)),
  S0_beta      := ((1 : ℚ) / (1 : ℚ)),
  kernelId     := "beta_demo_v1",
  windows      := [],
  tailRMSBound := ((0 : ℚ) / (1 : ℚ))
}

noncomputable def globalInertiaCertificate_beta_numeric : GlobalInertiaCertificate_beta :=
{
  C_Global_beta := ((1 : ℚ) / (10 : ℚ)),
  S0_global     := ((1 : ℚ) / (1 : ℚ)),
  Smax_global   := ((1 : ℚ) / (1 : ℚ)),
  sRef          := ((1 : ℚ) / (1 : ℚ))
}

noncomputable def strongInertiaComposite_beta_numeric : StrongInertiaComposite_beta :=
{
  localCert  := strongInertiaCertificate_beta_numeric,
  globalCert := globalInertiaCertificate_beta_numeric,
  kernelId   := "beta_demo_v1"
}

theorem strongInertiaCertificate_beta_numeric_correct :
    StrongInertiaCertificateCorrect_beta strongInertiaCertificate_beta_numeric := by
  dsimp [StrongInertiaCertificateCorrect_beta, strongInertiaCertificate_beta_numeric]
  refine And.intro ?hC ?hrest
  · norm_num
  · refine And.intro ?hS0 ?hrest2
    · norm_num
    · refine And.intro ?hWindows ?hrest3
      · simp
      · refine And.intro ?hRms ?hTail
        · simp
        · have hC_nonneg : (0:ℝ) ≤ (((1 : ℚ) / (10 : ℚ)) : ℝ) := by
            norm_num
          have hExp_nonneg : (0:ℝ) ≤ Real.exp (- ((((1 : ℚ) / (1 : ℚ)) : ℝ) / 2)) := by
            exact le_of_lt (Real.exp_pos _)
          have hSq_nonneg : (0:ℝ) ≤ ((((1 : ℚ) / (1 : ℚ)) : ℝ) ^ 2) := by
            norm_num
          have hCE : 0 ≤ (((1 : ℚ) / (10 : ℚ)) : ℝ) * Real.exp (-((((1 : ℚ) / (1 : ℚ)) : ℝ) / 2)) := by
            exact mul_nonneg hC_nonneg hExp_nonneg
          have hProd : 0 ≤ (((1 : ℚ) / (10 : ℚ)) : ℝ) * Real.exp (-((((1 : ℚ) / (1 : ℚ)) : ℝ) / 2)) * ((((1 : ℚ) / (1 : ℚ)) : ℝ) ^ 2) := by
            exact mul_nonneg hCE hSq_nonneg
          simpa using hProd

theorem globalInertiaCertificate_beta_numeric_correct :
    GlobalInertiaCertificateCorrect_beta globalInertiaCertificate_beta_numeric := by
  dsimp [GlobalInertiaCertificateCorrect_beta, globalInertiaCertificate_beta_numeric]
  constructor
  · norm_num
  constructor
  · norm_num
  · norm_num

theorem strongInertiaComposite_beta_numeric_correct :
    StrongInertiaCompositeCorrect_beta strongInertiaComposite_beta_numeric := by
  exact And.intro strongInertiaCertificate_beta_numeric_correct 
    globalInertiaCertificate_beta_numeric_correct

end Beta
end ERURH
