-- This file is auto-generated by tools.make_flux_bounds.py.
-- Do not edit manually.

import Mathlib
import ERURH.Flux
import ERURH.FluxWindows

namespace ERURH

open Classical
open scoped Rat

private noncomputable def logR_q_of_window : Window → ℚ :=
  fun _ => ((35010938607 : ℚ) / 200000000000)

private noncomputable def jRel_q_of_window : Window → ℚ :=
  fun _ => ((49287667 : ℚ) / 62500000000)

/-- Flux laws certified from the released numerical artefacts. -/
noncomputable def alphaFluxLaws :
    FluxLaws alphaBridge (alphaCoverCertificate alphaBridge rfl) :=
  {
    logR_q := logR_q_of_window
    jRel_q := jRel_q_of_window
    logR_q_tail := ((17505486809 : ℚ) / 100000000000)
    jRel_q_tail := ((1363890281 : ℚ) / 200000000000)
    logR_law := by
      intro w _ x _
      have h : |((35010938607 : ℚ) / 200000000000 : ℝ)| ≤ ((35010938607 : ℚ) / 200000000000 : ℝ) := by
        norm_num
      simpa [alphaBridge, logR_q_of_window, logRBoundWindow] using h
    jRel_law := by
      intro w _ x _
      have h : |((49287667 : ℚ) / 62500000000 : ℝ)| ≤ ((49287667 : ℚ) / 62500000000 : ℝ) := by
        norm_num
      simpa [alphaBridge, jRel_q_of_window, jRelBoundWindow] using h
    logR_tail := by
      intro x _
      have h : |((35010938607 : ℚ) / 200000000000 : ℝ)| ≤
          |((17505486809 : ℚ) / 100000000000 : ℝ)| := by
        norm_num
      simpa [alphaBridge, logRBoundWindow] using h
    jRel_tail := by
      intro x _
      have h : |((49287667 : ℚ) / 62500000000 : ℝ)| ≤
          |((1363890281 : ℚ) / 200000000000 : ℝ)| := by
        norm_num
      simpa [alphaBridge, jRelBoundWindow] using h
  }

/-- Global flux certificate obtained from the alpha mosaic and tail bounds. -/
noncomputable def alphaFluxCertificate :
    FluxCertificate alphaBridge :=
  FluxCertificate.ofLaws alphaFluxLaws

/-- The numerical ERURH bridge satisfies the inertia predicate. -/
theorem alphaBridge_inertia : InertiaERU alphaBridge :=
  inertia_from_windows alphaFluxCertificate

end ERURH
