-- This file is auto-generated by tools.make_lambda_bounds.py.

import Mathlib
import ERURH.BoundsConfig
import ERURH.FluxWindows

namespace ERURH

open scoped Real

noncomputable section

/-- Upper bound for the rectangle height used in the Lambda witness. -/

noncomputable def lamTcap : ℚ := BoundsConfig.boundsTcap

/-- Window-wise bound for log |lambdaCore (crit t)|. -/

noncomputable def lam_log_q (w : Window) : ℚ :=
  if h : w = wAlpha51_shift1 then (0 : Rat)
  else (0 : Rat)

/-- Window-wise bound for |(lambdaCore' / lambdaCore) (crit t)|. -/

noncomputable def lam_j_q (w : Window) : ℚ :=
  if h : w = wAlpha51_shift1 then ((236210849359 : Rat) / 500000000000)
  else ((77318098983 : Rat) / 40000000000)

/-- Tail bound for log |lambdaCore (crit t)|. -/

noncomputable def lam_log_tail : ℚ := (0 : Rat)

/-- Tail bound for |(lambdaCore' / lambdaCore) (crit t)|. -/

noncomputable def lam_j_tail : ℚ := ((77318098983 : Rat) / 40000000000)

/-- Global logarithmic bound dominating windows y tail. -/

noncomputable def lam_log_sup : ℚ := (0 : Rat)

/-- Global derivative bound dominating windows y tail. -/

noncomputable def lam_j_sup : ℚ := ((77318098983 : Rat) / 40000000000)

@[simp] lemma lam_log_q_wAlpha51_shift1 : lam_log_q wAlpha51_shift1 = (0 : Rat) := by
  classical
  simp [lam_log_q]
@[simp] lemma lam_j_q_wAlpha51_shift1 : lam_j_q wAlpha51_shift1 = ((236210849359 : Rat) / 500000000000) := by
  classical
  norm_num [lam_j_q]
lemma lam_log_q_le_sup_wAlpha51_shift1 : lam_log_q wAlpha51_shift1 ≤ lam_log_sup := by
  classical
  norm_num [lam_log_q, lam_log_sup]
lemma lam_log_tail_le_sup : lam_log_tail ≤ lam_log_sup := by
  classical
  norm_num [lam_log_tail, lam_log_sup]
lemma lam_j_q_le_sup_wAlpha51_shift1 : lam_j_q wAlpha51_shift1 ≤ lam_j_sup := by
  classical
  norm_num [lam_j_q, lam_j_sup]
lemma lam_j_tail_le_sup : lam_j_tail ≤ lam_j_sup := by
  classical
  norm_num [lam_j_tail, lam_j_sup]
lemma lam_j_q_nonneg_wAlpha51_shift1 : 0 ≤ lam_j_q wAlpha51_shift1 := by
  classical
  norm_num [lam_j_q]
lemma lam_j_tail_nonneg : 0 ≤ lam_j_tail := by
  classical
  norm_num [lam_j_tail]
lemma lam_j_sup_nonneg : 0 ≤ lam_j_sup := by
  classical
  norm_num [lam_j_sup]
lemma tailStart_le_lamTcap : FluxWindows.tailStart ≤ lamTcap := by

  simpa [lamTcap] using BoundsConfig.tailStart_le_boundsTcap

lemma lamTcap_eq_bounds : lamTcap = BoundsConfig.boundsTcap := rfl


end
