-- This file is auto-generated by tools.make_prefactor_bounds.py.

import Mathlib
import ERURH.BoundsConfig
import ERURH.AlphaWindowCover
import ERURH.FluxWindows
import ERURH_Staging.LambdaClose_base
import ERURH_Staging.PrefactorClose_tail
import ERURH_Staging.PrefactorClose_wAlpha49_shift0_all
import ERURH_Staging.PrefactorClose_wAlpha49_shift1_all

namespace ERURH

open scoped Real

noncomputable section

noncomputable def pf_log_q_wAlpha49_shift0 : ℚ := ((974413429088416707 : ℚ) / (204800000000000000 : ℚ))
noncomputable def pf_log_q_wAlpha49_shift1 : ℚ := ((998120722102293697 : ℚ) / (204800000000000000 : ℚ))
noncomputable def pf_log_tail_q : ℚ := ((63852554371729108003367 : ℚ) / (5884235424000000000000 : ℚ))
noncomputable def pf_j_q_zero : ℚ := 0
noncomputable def pf_tail_arg_q : ℚ := 0

lemma pf_log_q_wAlpha49_shift0_nonneg : 0 ≤ pf_log_q_wAlpha49_shift0 := by
  have : (0 : ℚ) ≤ ((974413429088416707 : ℚ) / (204800000000000000 : ℚ)) := by
    norm_num
  simpa using this

lemma pf_log_q_wAlpha49_shift1_nonneg : 0 ≤ pf_log_q_wAlpha49_shift1 := by
  have : (0 : ℚ) ≤ ((998120722102293697 : ℚ) / (204800000000000000 : ℚ)) := by
    norm_num
  simpa using this

lemma pf_log_tail_q_nonneg : 0 ≤ pf_log_tail_q := by
  have : (0 : ℚ) ≤ ((63852554371729108003367 : ℚ) / (5884235424000000000000 : ℚ)) := by
    norm_num
  simpa using this

lemma pf_j_q_zero_nonneg : 0 ≤ pf_j_q_zero := by simpa
lemma pf_tail_arg_nonneg : 0 ≤ ((pf_tail_arg_q : ℚ) : ℝ) := by simpa

noncomputable def pf_log_q (w : Window) : ℚ :=
  if h0 : w = wAlpha49_shift0 then pf_log_q_wAlpha49_shift0
  else if h1 : w = wAlpha49_shift1 then pf_log_q_wAlpha49_shift1
  else pf_log_q_wAlpha49_shift1

noncomputable def pf_j_q (_w : Window) : ℚ := 0

noncomputable def pf_tail_log (_t : ℝ) : ℝ := ((pf_log_tail_q : ℚ) : ℝ)
noncomputable def pf_tail_arg (_t : ℝ) : ℝ := 0

lemma pf_log_pad_dominates_wAlpha49_shift0 :
    ∀ {t : ℝ}, t ∈ wAlpha49_shift0.IccR → Staging.prefactor_pad_fun t ≤ ((pf_log_q_wAlpha49_shift0 : ℚ) : ℝ) := by
  intro t ht
  simpa using Staging.pf_log_le_window_wAlpha49_shift0 ht

lemma pf_log_pad_dominates_wAlpha49_shift1 :
    ∀ {t : ℝ}, t ∈ wAlpha49_shift1.IccR → Staging.prefactor_pad_fun t ≤ ((pf_log_q_wAlpha49_shift1 : ℚ) : ℝ) := by
  intro t ht
  simpa using Staging.pf_log_le_window_wAlpha49_shift1 ht

lemma pf_log_pad_dominates_tail :
    ∀ {{t : ℝ}}, Staging.tailStartR ≤ t → t ≤ BoundsConfig.boundsTcapR →
      Staging.prefactor_pad_fun t ≤ ((pf_log_tail_q : ℚ) : ℝ) := by
  intro t ht_lo ht_hi
  have h := Staging.tail_pf_log_le_cap (t := t) ht_lo ht_hi
  simpa using h

end
