-- This file is auto-generated by tools.make_rational_bounds.py
-- Do not edit manually.

import Mathlib.Data.Rat.Init

namespace ERURH

structure QBound where
  num : Nat
  den : Nat
  den_pos : 0 < den
  deriving Repr

def QBound.toRat (q : QBound) : Rat :=
  Rat.ofInt (Int.ofNat q.num) / Rat.ofInt (Int.ofNat q.den)

@[simp] def maxWOverMinW : QBound :=
  {
    num := 700019545,
    den := 231771981,
    den_pos := by decide
  }

@[simp] def maxWOverMinWRat : Rat := maxWOverMinW.toRat

@[simp] def lAClosed : QBound :=
  {
    num := 52730753,
    den := 91024984,
    den_pos := by decide
  }

@[simp] def lAClosedRat : Rat := lAClosed.toRat

@[simp] def weightMin : QBound :=
  {
    num := 4659489267,
    den := 784876265,
    den_pos := by decide
  }

@[simp] def weightMinRat : Rat := weightMin.toRat

@[simp] def weightMax : QBound :=
  {
    num := 2901653316,
    den := 197542537,
    den_pos := by decide
  }

@[simp] def weightMaxRat : Rat := weightMax.toRat

@[simp] def hMin : QBound :=
  {
    num := 203107218,
    den := 744347501,
    den_pos := by decide
  }

@[simp] def hMinRat : Rat := hMin.toRat

@[simp] def kappaBookClosed : QBound :=
  {
    num := 16056372531,
    den := 483168826,
    den_pos := by decide
  }

@[simp] def kappaBookClosedRat : Rat := kappaBookClosed.toRat

@[simp] def cEnvelopeClosed : QBound :=
  {
    num := 43040528,
    den := 902400129,
    den_pos := by decide
  }

@[simp] def cEnvelopeClosedRat : Rat := cEnvelopeClosed.toRat

@[simp] def inflationFactor : QBound :=
  {
    num := 431254631,
    den := 426430182,
    den_pos := by decide
  }

@[simp] def inflationFactorRat : Rat := inflationFactor.toRat

@[simp] def s0Closed : QBound :=
  {
    num := 2604787528,
    den := 183882357,
    den_pos := by decide
  }

@[simp] def s0ClosedRat : Rat := s0Closed.toRat

@[simp] def lGlobalFormal : QBound :=
  {
    num := 175023520,
    den := 997862133,
    den_pos := by decide
  }

@[simp] def lGlobalFormalRat : Rat := lGlobalFormal.toRat

@[simp] def kappaLowFormal : QBound :=
  {
    num := 3700246603,
    den := 453011309,
    den_pos := by decide
  }

@[simp] def kappaLowFormalRat : Rat := kappaLowFormal.toRat

@[simp] def kappaHighFormal : QBound :=
  {
    num := 8883257317,
    den := 941661373,
    den_pos := by decide
  }

@[simp] def kappaHighFormalRat : Rat := kappaHighFormal.toRat

@[simp] def cEnvelopeFormal : QBound :=
  {
    num := 43040528,
    den := 902400129,
    den_pos := by decide
  }

@[simp] def cEnvelopeFormalRat : Rat := cEnvelopeFormal.toRat

def allBounds : List (Prod String QBound) :=
  [( "max_w_over_min_w", maxWOverMinW ), ( "L_A_closed", lAClosed ), ( "weight_min", weightMin ), ( "weight_max", weightMax ), ( "h_min", hMin ), ( "kappa_book_closed", kappaBookClosed ), ( "C_envelope_closed", cEnvelopeClosed ), ( "inflation_factor", inflationFactor ), ( "s0_closed", s0Closed ), ( "L_global_formal", lGlobalFormal ), ( "kappa_low_formal", kappaLowFormal ), ( "kappa_high_formal", kappaHighFormal ), ( "C_envelope_formal", cEnvelopeFormal )]

end ERURH
