-- This file is auto-generated by tools.make_zeta_bounds.py.

import Mathlib
import ERURH.BoundsConfig
import ERURH.FluxWindows

namespace ERURH

open scoped Real

noncomputable section

/-- Upper bound for the rectangle height used in the zeta witness. -/

noncomputable def zetaTcap : ℚ := BoundsConfig.boundsTcap

/-- Window-wise bound for log |ζ(crit t)|. -/

noncomputable def zeta_log_q (w : Window) : ℚ :=
  if h : w = wAlpha51_shift1 then ((1973102491 : ℚ) / 3906250000)
  else ((426435487679 : ℚ) / 250000000000)

/-- Window-wise bound for |(ζ'/ζ)(crit t)|. -/

noncomputable def zeta_j_q (w : Window) : ℚ :=
  if h : w = wAlpha51_shift1 then ((1169606798083 : ℚ) / 1000000000000)
  else ((6032211236253 : ℚ) / 50000000000)

/-- Tail bound for log |ζ(crit t)|. -/

noncomputable def zeta_log_tail : ℚ := ((426435487679 : ℚ) / 250000000000)

/-- Tail bound for |(ζ'/ζ)(crit t)|. -/

noncomputable def zeta_j_tail : ℚ := ((6032211236253 : ℚ) / 50000000000)

/-- Global logarithmic bound dominating windows y tail. -/

noncomputable def zeta_log_sup : ℚ := ((426435487679 : ℚ) / 250000000000)

/-- Global derivative bound dominating windows y tail. -/

noncomputable def zeta_j_sup : ℚ := ((6032211236253 : ℚ) / 50000000000)

@[simp] lemma zeta_log_q_wAlpha51_shift1 : zeta_log_q wAlpha51_shift1 = ((1973102491 : ℚ) / 3906250000) := by
  classical
  simp [zeta_log_q]
@[simp] lemma zeta_j_q_wAlpha51_shift1 : zeta_j_q wAlpha51_shift1 = ((1169606798083 : ℚ) / 1000000000000) := by
  classical
  simp [zeta_j_q]
lemma zeta_log_q_le_sup_wAlpha51_shift1 : zeta_log_q wAlpha51_shift1 ≤ zeta_log_sup := by
  classical
  simp [zeta_log_q, zeta_log_sup]
lemma zeta_log_tail_le_sup : zeta_log_tail ≤ zeta_log_sup := by
  classical
  simp [zeta_log_tail, zeta_log_sup]
lemma zeta_j_q_le_sup_wAlpha51_shift1 : zeta_j_q wAlpha51_shift1 ≤ zeta_j_sup := by
  classical
  simp [zeta_j_q, zeta_j_sup]
lemma zeta_j_tail_le_sup : zeta_j_tail ≤ zeta_j_sup := by
  classical
  simp [zeta_j_tail, zeta_j_sup]
lemma zeta_log_q_nonneg_wAlpha51_shift1 : 0 ≤ zeta_log_q wAlpha51_shift1 := by
  classical
  simp [zeta_log_q]
lemma zeta_log_tail_nonneg : 0 ≤ zeta_log_tail := by
  classical
  simp [zeta_log_tail]
lemma zeta_log_sup_nonneg : 0 ≤ zeta_log_sup := by
  classical
  simp [zeta_log_sup]
lemma zeta_j_q_nonneg_wAlpha51_shift1 : 0 ≤ zeta_j_q wAlpha51_shift1 := by
  classical
  simp [zeta_j_q]
lemma zeta_j_tail_nonneg : 0 ≤ zeta_j_tail := by
  classical
  simp [zeta_j_tail]
lemma zeta_j_sup_nonneg : 0 ≤ zeta_j_sup := by
  classical
  simp [zeta_j_sup]
lemma tailStart_le_zetaTcap : FluxWindows.tailStart ≤ zetaTcap := by

  simpa [zetaTcap] using BoundsConfig.tailStart_le_boundsTcap

lemma zetaTcap_eq_bounds : zetaTcap = BoundsConfig.boundsTcap := rfl


end
