import Mathlib
import Mathlib.Data.Real.Basic
import Mathlib.Data.Complex.Basic
import Mathlib.Data.Complex.Abs
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Analysis.SpecialFunctions.Complex.Log
import Mathlib.Analysis.SpecialFunctions.Gamma.Basic
import Mathlib.Analysis.Calculus.Deriv.Basic
import Mathlib.NumberTheory.LSeries.RiemannZeta
import ERURH.RH

/-!
Staging artefacts generated by the numerical toolchain expect the module
`ERURH.Numeric.Semantics`.  The concrete numeric content is baked directly
inside each auto-generated `_all.lean` file, so this file exposes the shared
Mathlib surface that those artefacts rely on.
-/

namespace ERURH
namespace Numeric
namespace Semantics

-- Intentional no-op namespace — all semantics live in the generated files.

end Semantics
end Numeric
end ERURH
