-- This file is auto-generated by tools.make_rms_context.py
-- Do not edit manually.

import Mathlib
import ERURH.ERURH_A2Hypotheses

def n_windows : Nat := 1

@[simp] def cEnvelopeCtxRat : ℚ := ((43040528) : ℚ) / (902400129)
@[simp] def cLowRat : ℚ := ((1) : ℚ) / (10)
@[simp] def cTailRat : ℚ := ((1) : ℚ) / (10)

def cEnvelopeCtx : ℝ := (cEnvelopeCtxRat : ℝ)
def cLow : ℝ := (cLowRat : ℝ)
def cTail : ℝ := (cTailRat : ℝ)

def rmsModeList : List ℚ := [((1332805409) : ℚ) / (9024001290)]
def rmsLowList : List ℚ := [((1) : ℚ) / (20)]
def rmsTailList : List ℚ := [((1) : ℚ) / (20)]

def rmsModeRat (w : Fin n_windows) : ℚ := by
  refine rmsModeList.get ⟨w.1, ?_⟩
  simpa [rmsModeList, n_windows] using w.isLt

def rmsLowRat (w : Fin n_windows) : ℚ := by
  refine rmsLowList.get ⟨w.1, ?_⟩
  simpa [rmsLowList, n_windows] using w.isLt

def rmsTailRat (w : Fin n_windows) : ℚ := by
  refine rmsTailList.get ⟨w.1, ?_⟩
  simpa [rmsTailList, n_windows] using w.isLt


def rmsMode (w : Fin n_windows) : ℝ := (rmsModeRat w : ℝ)

def rmsLow (w : Fin n_windows) : ℝ := (rmsLowRat w : ℝ)

def rmsTail (w : Fin n_windows) : ℝ := (rmsTailRat w : ℝ)


def ctx_real : _root_.ERURH.RMSLocalContext :=
  { Window := Fin n_windows
    RMS_alpha := fun _ => cEnvelopeCtx
    RMS_mode := rmsMode
    RMS_low := rmsLow
    RMS_tail := rmsTail
    c_low := cLow
    c_tail := cTail
    c_low_nonneg := by
      norm_num [cLow, cLowRat]
    c_tail_nonneg := by
      norm_num [cTail, cTailRat]
    RMS_tail_bound_simple := by
      intro w
      fin_cases w <;> norm_num [rmsTail, rmsTailRat, rmsTailList, cTail, cTailRat, n_windows]
    RMS_decomp := by
      intro w
      fin_cases w <;> norm_num [rmsMode, rmsLow, rmsTail, rmsModeRat, rmsLowRat, rmsTailRat, rmsModeList, rmsLowList, rmsTailList, cEnvelopeCtx, cEnvelopeCtxRat, n_windows]
  }

theorem ctx_real_A2Low : _root_.ERURH.A2Low_RMS ctx_real := by
  dsimp [_root_.ERURH.A2Low_RMS, ctx_real]
  intro w
  fin_cases w <;> norm_num [rmsLow, rmsLowRat, rmsLowList, cLow, cLowRat, n_windows]

theorem ctx_real_A2Tail : _root_.ERURH.A2Tail_RMS ctx_real := by
  simpa [_root_.ERURH.A2Tail_RMS] using ctx_real.RMS_tail_bound_simple

abbrev ERURH.Alpha.GeneratedRMSContext.ctx_real : _root_.ERURH.RMSLocalContext := _root_.ctx_real
abbrev ERURH.Alpha.GeneratedRMSContext.ctx_real_A2Low : _root_.ERURH.A2Low_RMS ERURH.Alpha.GeneratedRMSContext.ctx_real := _root_.ctx_real_A2Low
abbrev ERURH.Alpha.GeneratedRMSContext.ctx_real_A2Tail : _root_.ERURH.A2Tail_RMS ERURH.Alpha.GeneratedRMSContext.ctx_real := _root_.ctx_real_A2Tail
