-- This file is auto-generated by tools.make_rms_mode_bridge.py
-- Do not edit manually.

import Mathlib
import ERURH.ERUModesCore
import ERURH.Alpha.GeneratedRMSContext
import ERURH.Alpha.RMSModeSemantic

def sWitList : List ℚ := [((6907755278982137) : ℚ) / (500000000000000)]
def uWitList : List ℚ := [((1332805409) : ℚ) / (9024001290)]

def sWitRat (w : Fin n_windows) : ℚ := by
  refine sWitList.get ⟨w.1, ?_⟩
  simpa [sWitList, n_windows] using w.isLt

def uWitRat (w : Fin n_windows) : ℚ := by
  refine uWitList.get ⟨w.1, ?_⟩
  simpa [uWitList, n_windows] using w.isLt


def sWit (w : Fin n_windows) : ℝ := (sWitRat w : ℝ)

def uWit (w : Fin n_windows) : ℝ := (uWitRat w : ℝ)

theorem sWit_mem_interval (w : Fin n_windows) :
    sWit w ∈ ERURH.Alpha.GeneratedRMSContext.ctx_real_window_interval w := by
  dsimp [ERURH.Alpha.GeneratedRMSContext.ctx_real_window_interval, window_interval]
  fin_cases w <;>
    norm_num [sWit, sWitRat, sWitList, windowMin, windowMinRat, windowMinList, windowMax, windowMaxRat, windowMaxList, n_windows]

theorem uWit_le_rms_mode (w : Fin n_windows) :
    uWit w ≤ ERURH.Alpha.GeneratedRMSContext.ctx_real.RMS_mode w := by
  fin_cases w <;> simpa [uWit, uWitRat, uWitList, rmsMode, rmsModeRat, rmsModeList, ERURH.Alpha.GeneratedRMSContext.ctx_real, ctx_real, n_windows]

def ctx_real_logR_alpha_upper (w : Fin n_windows) : Prop :=
  |ERURH.logR_alpha (sWit w)| ≤ uWit w

theorem ctx_real_rms_mode_ge_semantic (w : Fin n_windows)
    (h_upper : ctx_real_logR_alpha_upper w) :
    ERURH.Alpha.GeneratedRMSContext.ctx_real.RMS_mode w ≥
      ERURH.Alpha.rms_semantic w := by
  have h_mem : |ERURH.logR_alpha (sWit w)| ∈ ERURH.Alpha.rms_semantic_values w := by
    exact ⟨sWit w, sWit_mem_interval w, rfl⟩
  have h_bdd : BddBelow (ERURH.Alpha.rms_semantic_values w) := by
    refine ⟨0, ?_⟩
    intro x hx
    rcases hx with ⟨s, hs, rfl⟩
    exact abs_nonneg _
  have h_inf_le : ERURH.Alpha.rms_semantic w ≤ |ERURH.logR_alpha (sWit w)| := by
    exact csInf_le h_bdd h_mem
  have h_inf_le' : ERURH.Alpha.rms_semantic w ≤ uWit w := le_trans h_inf_le h_upper
  exact le_trans h_inf_le' (uWit_le_rms_mode w)
