"""Generate rational bounds for formal constants."""

from __future__ import annotations

import argparse
import json
from decimal import Decimal
from fractions import Fraction
from pathlib import Path
from typing import Dict, Mapping, Optional, List

DEFAULT_RELEASE_DIR = Path("data") / "releases" / "erurh-v2-core" / "formal"
DEFAULT_OUT = Path("data") / "docs" / "paper" / "rational_bounds.json"


def _load_json(path: Path) -> Dict[str, object]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise FileNotFoundError(f"Missing artefact: {path}") from exc
    except json.JSONDecodeError as exc:
        raise ValueError(f"Malformed JSON in {path}: {exc}") from exc


def _get_decimal(mapping: Mapping[str, object], key: str, *, source: str) -> Decimal:
    if key not in mapping:
        raise KeyError(f"Key '{key}' missing in {source}")
    value = mapping[key]
    if isinstance(value, (int, float, Decimal)):
        return Decimal(str(value))
    if isinstance(value, str):
        return Decimal(value)
    raise TypeError(f"Unsupported value for {key} in {source}: {type(value)}")


def _fraction_payload(value: Decimal, *, limit: int = 10**9) -> Dict[str, object]:
    fraction = Fraction(value).limit_denominator(limit)
    return {
        "decimal": format(value, "f"),
        "numerator": fraction.numerator,
        "denominator": fraction.denominator,
    }


def build_bounds(release_dir: Path) -> Dict[str, object]:
    L_proof = _load_json(release_dir / "L_analytic_proof.json")
    kappa_proof = _load_json(release_dir / "kappa_book_proof.json")
    bridge_proof = _load_json(release_dir / "bridge_closed.json")
    s0_unified = _load_json(release_dir / "s0_unified.json")
    formal_report = _load_json(release_dir / "formal_report_strict.json")

    worst_patch = L_proof.get("worst_patch")
    if not isinstance(worst_patch, Mapping):
        raise ValueError("L_analytic_proof.json missing 'worst_patch'.")

    bounds = {
        "max_w_over_min_w": _fraction_payload(
            _get_decimal(worst_patch, "max_w_over_min_w", source="L_analytic_proof.worst_patch")
        ),
        "L_A_closed": _fraction_payload(
            _get_decimal(worst_patch, "L_A_closed", source="L_analytic_proof.worst_patch")
        ),
        "weight_min": _fraction_payload(_get_decimal(kappa_proof, "weight_min", source="kappa_book_proof")),
        "weight_max": _fraction_payload(_get_decimal(kappa_proof, "weight_max", source="kappa_book_proof")),
        "h_min": _fraction_payload(_get_decimal(kappa_proof, "h_min", source="kappa_book_proof")),
        "kappa_book_closed": _fraction_payload(
            _get_decimal(kappa_proof, "kappa_book_closed", source="kappa_book_proof")
        ),
        "C_envelope_closed": _fraction_payload(
            _get_decimal(bridge_proof, "C_envelope_closed", source="bridge_closed")
        ),
        "inflation_factor": _fraction_payload(
            _get_decimal(bridge_proof, "inflation_factor", source="bridge_closed")
        ),
        "s0_closed": _fraction_payload(_get_decimal(s0_unified, "s0_closed", source="s0_unified")),
        "L_global_formal": _fraction_payload(
            _get_decimal(formal_report, "L_global_formal", source="formal_report_strict")
        ),
        "kappa_low_formal": _fraction_payload(
            _get_decimal(formal_report, "kappa_low_formal", source="formal_report_strict")
        ),
        "kappa_high_formal": _fraction_payload(
            _get_decimal(formal_report, "kappa_high_formal", source="formal_report_strict")
        ),
        "C_envelope_formal": _fraction_payload(
            _get_decimal(formal_report, "C_envelope_formal", source="formal_report_strict")
        ),
    }

    payload = {
        "bounds": bounds,
        "sources": {
            "L_analytic_proof": str((release_dir / "L_analytic_proof.json").resolve()),
            "kappa_book_proof": str((release_dir / "kappa_book_proof.json").resolve()),
            "bridge_closed": str((release_dir / "bridge_closed.json").resolve()),
            "s0_unified": str((release_dir / "s0_unified.json").resolve()),
            "formal_report_strict": str((release_dir / "formal_report_strict.json").resolve()),
        },
    }
    return payload


def _key_to_name(key: str) -> str:
    parts = key.split("_")
    if not parts:
        return key
    first = parts[0].lower()
    rest = "".join(part.capitalize() for part in parts[1:])
    return first + rest




def write_lean_module(bounds: Mapping[str, Mapping[str, object]], lean_path: Path) -> None:
    lines: List[str] = []
    lines.append("-- This file is auto-generated by tools.make_rational_bounds.py")
    lines.append("-- Do not edit manually.")
    lines.append("")
    lines.append("import Mathlib.Data.Rat.Init")
    lines.append("")
    lines.append("namespace ERURH")
    lines.append("")
    lines.append("structure QBound where")
    lines.append("  num : Nat")
    lines.append("  den : Nat")
    lines.append("  den_pos : 0 < den\n  deriving Repr")
    lines.append("")
    lines.append("def QBound.toRat (q : QBound) : Rat :=")
    lines.append("  Rat.ofInt (Int.ofNat q.num) / Rat.ofInt (Int.ofNat q.den)")
    lines.append("")

    all_entries: List[str] = []
    for key, data in bounds.items():
        name = _key_to_name(key)
        num = int(data["numerator"])
        den = int(data["denominator"])
        lines.append(f"@[simp] def {name} : QBound :=")
        lines.append("  {")
        lines.append(f"    num := {num},")
        lines.append(f"    den := {den},")
        lines.append("    den_pos := by decide")
        lines.append("  }")
        lines.append("")
        lines.append(f"@[simp] def {name}Rat : Rat := {name}.toRat")
        lines.append("")
        all_entries.append(f'( "{key}", {name} )')

    lines.append("def allBounds : List (Prod String QBound) :=")
    lines.append(f"  [{', '.join(all_entries)}]")
    lines.append("")
    lines.append("end ERURH")
    lines.append("")
    lean_path.write_text('\n'.join(lines), encoding='utf-8')


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate rational bounds JSON for Lean/Coq integration.")
    parser.add_argument(
        "--release-dir",
        type=Path,
        default=DEFAULT_RELEASE_DIR,
        help="Directory containing formal proof JSON artefacts.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT,
        help="Destination JSON path.",
    )
    parser.add_argument(
        "--lean-out",
        type=Path,
        default=Path("lean") / "formal_proofs" / "ERURH" / "RationalBounds.lean",
        help="Optional Lean module path to mirror the bounds.",
    )
    args = parser.parse_args()

    payload = build_bounds(args.release_dir.resolve())
    bounds = payload["bounds"]
    args.out.resolve().parent.mkdir(parents=True, exist_ok=True)
    args.out.resolve().write_text(json.dumps(payload, indent=2), encoding="utf-8")
    if args.lean_out:
        args.lean_out.resolve().parent.mkdir(parents=True, exist_ok=True)
        write_lean_module(bounds, args.lean_out.resolve())


if __name__ == "__main__":
    main()

