"""Generate RMS-mode bridge artefacts for Route B."""

from __future__ import annotations

import argparse
import json
from decimal import Decimal
from fractions import Fraction
from pathlib import Path
from typing import Dict, List, Mapping, Sequence

DEFAULT_RELEASE_DIR = Path("data") / "releases" / "erurh-v2-core" / "formal"
DEFAULT_IN_FILE = "rms_mode_bridge.json"
DEFAULT_OUT_JSON = Path("data") / "docs" / "paper" / "rms_mode_bridge.json"
DEFAULT_LEAN_OUT = (
    Path("lean") / "formal_proofs" / "ERURH" / "Alpha" / "GeneratedRMSModeBridge.lean"
)
SCHEMA_VERSION = "rms_mode_bridge_schema_v1"


def _load_json(path: Path) -> Dict[str, object]:
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise FileNotFoundError(f"Missing RMS mode bridge artefact: {path}") from exc
    try:
        return json.loads(text, parse_float=Decimal)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Malformed JSON in {path}: {exc}") from exc


def _parse_rational(value: object, *, label: str) -> Fraction:
    if isinstance(value, Fraction):
        return value
    if isinstance(value, Decimal):
        return Fraction(value)
    if isinstance(value, int):
        return Fraction(value, 1)
    if isinstance(value, float):
        return Fraction(Decimal(str(value)))
    if isinstance(value, str):
        if "/" in value:
            num_str, den_str = value.split("/", 1)
            num = int(num_str.strip())
            den = int(den_str.strip())
            if den == 0:
                raise ValueError(f"{label} has zero denominator")
            return Fraction(num, den)
        return Fraction(Decimal(value))
    raise TypeError(f"{label} must be a rational string or number, got {type(value)!r}")


def _fraction_to_str(value: Fraction) -> str:
    if value.denominator == 1:
        return f"{value.numerator}/1"
    return f"{value.numerator}/{value.denominator}"


def _rat_literal(value: Fraction) -> str:
    num = value.numerator
    den = value.denominator
    return f"(({num}) : ℚ) / ({den})"


def _validate_schema(data: Mapping[str, object]) -> Dict[str, object]:
    if data.get("version") != SCHEMA_VERSION:
        raise ValueError(f"Expected version '{SCHEMA_VERSION}', got '{data.get('version')}'")
    windows = data.get("windows")
    if not isinstance(windows, list) or not windows:
        raise ValueError("windows must be a nonempty list")
    allowed_keys = {"id", "s_wit", "u_wit"}
    ids = set()
    for entry in windows:
        if not isinstance(entry, Mapping):
            raise TypeError("Each window entry must be an object")
        extra = set(entry.keys()) - allowed_keys
        if extra:
            raise KeyError(f"Unexpected keys in window entry: {sorted(extra)}")
        if "id" not in entry:
            raise KeyError("Each window entry must have an id")
        if not isinstance(entry["id"], int):
            raise TypeError("Window id must be an integer")
        ids.add(entry["id"])
        for key in ("s_wit", "u_wit"):
            if key not in entry:
                raise KeyError(f"Window entry missing '{key}'")
    return dict(data)


def _normalize_payload(data: Mapping[str, object]) -> Dict[str, object]:
    payload = _validate_schema(data)
    windows = list(payload["windows"])
    windows.sort(key=lambda w: int(w["id"]))

    def normalize_entry(entry: Mapping[str, object]) -> Dict[str, object]:
        out: Dict[str, object] = {"id": int(entry["id"])}
        out["s_wit"] = _fraction_to_str(_parse_rational(entry["s_wit"], label="s_wit"))
        out["u_wit"] = _fraction_to_str(_parse_rational(entry["u_wit"], label="u_wit"))
        return out

    return {
        "version": payload["version"],
        "windows": [normalize_entry(w) for w in windows],
    }


def _emit_list(name: str, values: Sequence[Fraction]) -> List[str]:
    entries = ", ".join(_rat_literal(value) for value in values)
    return [f"def {name} : List ℚ := [{entries}]"]


def _emit_lookup(name: str, list_name: str) -> List[str]:
    return [
        f"def {name} (w : Fin n_windows) : ℚ := by",
        f"  refine {list_name}.get ⟨w.1, ?_⟩",
        f"  simpa [{list_name}, n_windows] using w.isLt",
        "",
    ]


def _emit_cast(name: str, rat_name: str) -> List[str]:
    return [f"def {name} (w : Fin n_windows) : ℝ := ({rat_name} w : ℝ)", ""]


def write_lean_module(payload: Mapping[str, object], lean_path: Path) -> None:
    windows = list(payload["windows"])
    windows.sort(key=lambda w: int(w["id"]))

    s_wit_vals = [_parse_rational(w["s_wit"], label="s_wit") for w in windows]
    u_wit_vals = [_parse_rational(w["u_wit"], label="u_wit") for w in windows]

    lines: List[str] = []
    lines.append("-- This file is auto-generated by tools.make_rms_mode_bridge.py")
    lines.append("-- Do not edit manually.")
    lines.append("")
    lines.append("import Mathlib")
    lines.append("import ERURH.ERUModesCore")
    lines.append("import ERURH.Alpha.GeneratedRMSContext")
    lines.append("import ERURH.Alpha.RMSModeSemantic")
    lines.append("")
    lines += _emit_list("sWitList", s_wit_vals)
    lines += _emit_list("uWitList", u_wit_vals)
    lines.append("")
    lines += _emit_lookup("sWitRat", "sWitList")
    lines += _emit_lookup("uWitRat", "uWitList")
    lines.append("")
    lines += _emit_cast("sWit", "sWitRat")
    lines += _emit_cast("uWit", "uWitRat")
    lines.append("theorem sWit_mem_interval (w : Fin n_windows) :")
    lines.append("    sWit w ∈ ERURH.Alpha.GeneratedRMSContext.ctx_real_window_interval w := by")
    lines.append("  dsimp [ERURH.Alpha.GeneratedRMSContext.ctx_real_window_interval, window_interval]")
    lines.append("  fin_cases w <;>")
    lines.append(
        "    norm_num [sWit, sWitRat, sWitList, windowMin, windowMinRat, windowMinList,"
        " windowMax, windowMaxRat, windowMaxList, n_windows]"
    )
    lines.append("")
    lines.append("theorem uWit_le_rms_mode (w : Fin n_windows) :")
    lines.append("    uWit w ≤ ERURH.Alpha.GeneratedRMSContext.ctx_real.RMS_mode w := by")
    lines.append(
        "  fin_cases w <;> simpa [uWit, uWitRat, uWitList, rmsMode, rmsModeRat,"
        " rmsModeList, ERURH.Alpha.GeneratedRMSContext.ctx_real, ctx_real, n_windows]"
    )
    lines.append("")
    lines.append("def ctx_real_logR_alpha_upper (w : Fin n_windows) : Prop :=")
    lines.append("  |ERURH.logR_alpha (sWit w)| ≤ uWit w")
    lines.append("")
    lines.append("theorem ctx_real_rms_mode_ge_semantic (w : Fin n_windows)")
    lines.append("    (h_upper : ctx_real_logR_alpha_upper w) :")
    lines.append("    ERURH.Alpha.GeneratedRMSContext.ctx_real.RMS_mode w ≥")
    lines.append("      ERURH.Alpha.rms_semantic w := by")
    lines.append("  have h_mem : |ERURH.logR_alpha (sWit w)| ∈ ERURH.Alpha.rms_semantic_values w := by")
    lines.append("    exact ⟨sWit w, sWit_mem_interval w, rfl⟩")
    lines.append("  have h_bdd : BddBelow (ERURH.Alpha.rms_semantic_values w) := by")
    lines.append("    refine ⟨0, ?_⟩")
    lines.append("    intro x hx")
    lines.append("    rcases hx with ⟨s, hs, rfl⟩")
    lines.append("    exact abs_nonneg _")
    lines.append("  have h_inf_le : ERURH.Alpha.rms_semantic w ≤ |ERURH.logR_alpha (sWit w)| := by")
    lines.append("    exact csInf_le h_bdd h_mem")
    lines.append("  have h_inf_le' : ERURH.Alpha.rms_semantic w ≤ uWit w := le_trans h_inf_le h_upper")
    lines.append("  exact le_trans h_inf_le' (uWit_le_rms_mode w)")
    lines.append("")

    lean_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate RMS-mode bridge artefacts for ERURH.")
    parser.add_argument(
        "--release-dir",
        type=Path,
        default=DEFAULT_RELEASE_DIR,
        help="Directory containing frozen RMS-mode bridge JSON.",
    )
    parser.add_argument(
        "--in",
        dest="in_file",
        type=str,
        default=DEFAULT_IN_FILE,
        help="Input RMS-mode bridge JSON filename (within release-dir).",
    )
    parser.add_argument(
        "--out-json",
        type=Path,
        default=DEFAULT_OUT_JSON,
        help="Destination JSON path.",
    )
    parser.add_argument(
        "--lean-out",
        type=Path,
        default=DEFAULT_LEAN_OUT,
        help="Destination Lean module path.",
    )
    args = parser.parse_args()

    input_path = args.release_dir / args.in_file
    payload = _load_json(input_path)
    normalized = _normalize_payload(payload)

    args.out_json.resolve().parent.mkdir(parents=True, exist_ok=True)
    args.out_json.resolve().write_text(json.dumps(normalized, indent=2), encoding="utf-8")

    if args.lean_out:
        args.lean_out.resolve().parent.mkdir(parents=True, exist_ok=True)
        write_lean_module(normalized, args.lean_out.resolve())


if __name__ == "__main__":
    main()
